steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-api', './flask-api']
  
  # Push Docker image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-api']
  
  # Deploy ke Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'flask-api',
      '--image', 'gcr.io/$PROJECT_ID/flask-api',
      '--region', 'asia-southeast2',
      '--allow-unauthenticated'
    ]
images:
  - 'gcr.io/$PROJECT_ID/flask-api'
